### ISSUE TITLE
Possible changes

### ISSUE THREAD

**Issue by igarizio** [zlavogb/data-598a-replication-project#1]
Today we talked with @advika18 about possible changes/modifications to the code:
- [x] Change percentile definition for rich and poor countries.
- [x] Change seed in bootstrap (the problem is that this is only part of the STATA code).
- [ ] Change forecast year 2100 to a different year (at least in figure 3).

**Comment by advika18** [comment]
The latest code has a new percentile threshold of 42% and a revised seed. We can play around with the forecast year in the R code, I believe.
